import type { CompatAxis, CompatFinding, ManualSession, PlatformSelector } from '../schema'

// Render the matrix as a human-readable guide. The generator is pure and
// deterministic: the same findings always produce the same markdown, so the
// committed guide only changes when the data changes.

const AXIS_TITLES: Record<CompatAxis, string> = {
  'embedding-context': 'Embedding context',
  'transport-security': 'Transport security',
  'credential-storage': 'Credential storage',
  authenticator: 'Authenticator',
  'capability-flag': 'Capability flags',
  'cross-device': 'Cross-device',
}

// Ordered so the guide reads from "where you run" outward to specific capabilities.
const AXIS_ORDER: readonly CompatAxis[] = [
  'transport-security',
  'embedding-context',
  'authenticator',
  'credential-storage',
  'cross-device',
  'capability-flag',
]

const OUTCOME_LABELS = {
  works: '✅ works',
  partial: '⚠️ partial',
  fails: '❌ fails',
  unsupported: '⛔ unsupported',
} as const

export interface GuideOptions {
  /** "Data as of" stamp shown in the header. */
  asOf: string
  /** Real-hardware sessions to publish alongside the findings. */
  sessions?: readonly ManualSession[]
}

export function generateGuide(findings: readonly CompatFinding[], options: GuideOptions): string {
  const lines: string[] = []

  lines.push('# Stellar Passkey Compatibility Guide')
  lines.push('')
  lines.push(
    '> Generated from `packages/compat/src/data`. Do not edit this file by hand — change the data and regenerate.',
  )
  lines.push('')
  lines.push(`Data as of **${options.asOf}**.`)
  lines.push('')
  lines.push(
    'This guide records where passkey flows work across browsers, operating systems, authenticators, and embedding contexts, why they break when they do, and the fallback a wallet should take. The SDK reads the same dataset to choose its runtime fallbacks, so the guidance here and the code cannot drift apart.',
  )
  lines.push('')

  lines.push('## How to read this')
  lines.push('')
  lines.push('Every finding carries a verification status:')
  lines.push('')
  lines.push(
    '- **documented** — sourced from specifications, vendor documentation, or issue trackers, and not yet re-confirmed on real hardware by this project.',
  )
  lines.push('- **automated** — exercised by the CI virtual-authenticator harness.')
  lines.push('- **manual-device** — confirmed by hand on a named real device.')
  lines.push('')
  lines.push(
    'Outcomes are one of ✅ works, ⚠️ partial, ❌ fails, or ⛔ unsupported. A last-verified date sits on every entry so you can see what is fresh.',
  )
  lines.push('')

  for (const axis of AXIS_ORDER) {
    const inAxis = findings.filter((finding) => finding.axis === axis)
    if (inAxis.length === 0) continue

    lines.push(`## ${AXIS_TITLES[axis]}`)
    lines.push('')

    for (const finding of inAxis) {
      lines.push(`### ${finding.title}`)
      lines.push('')
      lines.push(
        `${OUTCOME_LABELS[finding.outcome]} · feature: \`${finding.feature}\` · ${finding.verification.method}, verified ${finding.verification.lastVerified}`,
      )
      lines.push('')
      lines.push(`**Applies to:** ${describePlatforms(finding.platforms)}`)
      lines.push('')
      lines.push(`**What happens:** ${finding.cause}`)
      lines.push('')
      lines.push(`**Fallback:** ${finding.fallback}`)
      lines.push('')
      lines.push(`**Recommendation:** ${finding.recommendation}`)
      lines.push('')
      if (finding.runtime)
        lines.push(
          `**SDK rule:** on \`${finding.runtime.condition}\`, take \`${finding.runtime.action}\`.`,
        )
      if (finding.runtime) lines.push('')
      lines.push('Sources:')
      for (const source of finding.sources) lines.push(`- ${source}`)
      lines.push('')
    }
  }

  if (options.sessions && options.sessions.length > 0) {
    lines.push('## Verified device sessions')
    lines.push('')
    lines.push(
      'Real-hardware tests of the reference demo. Each entry records only what the tester actually confirmed.',
    )
    lines.push('')
    lines.push('| Date | Device | Browser | Authenticator | Outcome | Confirmed |')
    lines.push('| ---- | ------ | ------- | ------------- | ------- | --------- |')
    for (const session of options.sessions)
      lines.push(
        `| ${session.date} | ${session.device} (${session.os}) | ${session.browser} | ${session.authenticator} | ${OUTCOME_LABELS[session.outcome]} | ${session.confirmed} |`,
      )
    lines.push('')
  }

  lines.push('## Maintenance')
  lines.push('')
  lines.push(
    'The matrix lives as structured data and is regenerated, not edited. Entries marked **documented** are awaiting confirmation by the automated harness (virtual authenticators in CI) and the manual device lab; as those run, entries move to **automated** or **manual-device** and their dates advance. An entry that has not been re-verified within the review window is a signal to re-check it, not a guarantee it still holds.',
  )
  lines.push('')

  return lines.join('\n')
}

function describePlatforms(platforms: PlatformSelector): string {
  const parts: string[] = []
  if (platforms.browsers && platforms.browsers.length > 0) parts.push(platforms.browsers.join(', '))
  if (platforms.operatingSystems && platforms.operatingSystems.length > 0)
    parts.push(`on ${platforms.operatingSystems.join(', ')}`)
  return parts.length > 0 ? parts.join(' ') : 'all platforms'
}
