import {
  type CompatFinding,
  FALLBACK_ACTIONS,
  type FallbackActionId,
  type Outcome,
  RUNTIME_CONDITIONS,
  type RuntimeConditionId,
  type WebAuthnFeature,
} from '../schema'

// A runtime fallback rule: the actionable distillation of a finding. Only findings
// the SDK can actually detect and respond to become rules; informational findings
// (recovery guidance, attestation policy) stay in the guide.
export interface CompatRule {
  id: string
  condition: RuntimeConditionId
  action: FallbackActionId
  feature: WebAuthnFeature
  outcome: Outcome
  reason: string
  sources: readonly string[]
  lastVerified: string
}

export function deriveRules(findings: readonly CompatFinding[]): CompatRule[] {
  const rules: CompatRule[] = []
  for (const finding of findings) {
    if (!finding.runtime) continue
    rules.push({
      id: finding.id,
      condition: finding.runtime.condition,
      action: finding.runtime.action,
      feature: finding.feature,
      outcome: finding.outcome,
      reason: finding.cause,
      sources: finding.sources,
      lastVerified: finding.verification.lastVerified,
    })
  }
  return rules
}

export interface EmitOptions {
  asOf: string
}

/**
 * Emit the self-contained TypeScript module that the core SDK consumes. The
 * module carries its own types so core depends on nothing from this package at
 * runtime — it imports a plain, generated data file.
 */
export function emitRulesModule(rules: readonly CompatRule[], options: EmitOptions): string {
  const conditionUnion = unionType(RUNTIME_CONDITIONS)
  const actionUnion = unionType(FALLBACK_ACTIONS)

  const out: string[] = []
  out.push('// AUTO-GENERATED by @passkey-ui/compat. Do not edit by hand.')
  out.push('// Source of truth: packages/compat/src/data')
  out.push(`// Data as of: ${options.asOf}`)
  out.push('')
  out.push('/** A runtime condition the SDK can detect. */')
  out.push(`export type RuntimeConditionId = ${conditionUnion}`)
  out.push('')
  out.push('/** A fallback the SDK can take in response to a condition. */')
  out.push(`export type FallbackActionId = ${actionUnion}`)
  out.push('')
  out.push('export interface CompatRule {')
  out.push('  readonly id: string')
  out.push('  readonly condition: RuntimeConditionId')
  out.push('  readonly action: FallbackActionId')
  out.push('  readonly feature: string')
  out.push("  readonly outcome: 'works' | 'partial' | 'fails' | 'unsupported'")
  out.push('  readonly reason: string')
  out.push('  readonly sources: readonly string[]')
  out.push('  readonly lastVerified: string')
  out.push('}')
  out.push('')
  out.push('export const compatRules: readonly CompatRule[] = [')
  for (const rule of rules) out.push(emitRule(rule))
  out.push(']')
  out.push('')

  return out.join('\n')
}

function emitRule(rule: CompatRule): string {
  const sources = rule.sources.map((source) => `    ${str(source)},`).join('\n')
  return [
    '  {',
    `    id: ${str(rule.id)},`,
    `    condition: ${str(rule.condition)},`,
    `    action: ${str(rule.action)},`,
    `    feature: ${str(rule.feature)},`,
    `    outcome: ${str(rule.outcome)},`,
    `    reason: ${str(rule.reason)},`,
    '    sources: [',
    sources,
    '    ],',
    `    lastVerified: ${str(rule.lastVerified)},`,
    '  },',
  ].join('\n')
}

function unionType(values: readonly string[]): string {
  return values.map(str).join(' | ')
}

// JSON.stringify gives correctly escaped, double-quoted string literals, which
// TypeScript accepts. The generated file is excluded from formatting, so quote
// style does not matter here.
function str(value: string): string {
  return JSON.stringify(value)
}
